_commit: v0.0.12
_src_path: gh:huxuan/serious-scaffold-python
author_email: ''
author_name: you-n-g
module_name: gpttools
package_name: gpttools
project_description: GPT-based-tools
project_name: GPTBasedTools
repo_name: gpttools
repo_namespace: you-n-g
